---
- name: Create Windows Server in GCP
  hosts: localhost
  gather_facts: no
  
  vars:
    project_id: rhpds-345620
    zone: us-central1-a
    instance_name: windows-server-test
    machine_type: e2-standard-2
    source_image_family: windows-2022
    source_image_project: windows-cloud
    disk_size_gb: 50
    network: default

  tasks:
    - name: Create a Windows Server VM instance
      google.cloud.gcp_compute_instance:
        name: "{{ instance_name }}"
        machine_type: "{{ machine_type }}"
        zone: "{{ zone }}"
        project: "{{ project_id }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: "projects/{{ source_image_project }}/global/images/family/{{ source_image_family }}"
              disk_size_gb: "{{ disk_size_gb }}"
        network_interfaces:
          - network: "global/networks/{{ network }}"
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
        metadata:
          windows-startup-script-cmd: |
            net user /add ansible_user myPassword123!
            net localgroup administrators ansible_user /add
        service_accounts:
          - email: sa-openenv-9bkwf@rhpds-345620.iam.gserviceaccount.com
            scopes:
              - https://www.googleapis.com/auth/cloud-platform
        tags:
          - windows-server
      register: instance

    - name: Print instance public IP
      debug:
        var: instance.data.networkInterfaces[0].accessConfigs[0].natIP
