---
- name: Create a GCP instance
  hosts: localhost
  gather_facts: no
  
  vars:
    project_id: rhpds-345620
    cred_kind: serviceaccount

    # zone: us-central1-a
    # instance_name: windows-server-test
    # machine_type: e2-standard-2
    # source_image_family: windows-2022
    # source_image_project: windows-cloud
    # disk_size_gb: 50
    # network: default

  tasks:
    - name: create a disk maaped from RHEL8 image
      google.cloud.gcp_compute_disk:
        name: disk-instance
        size_gb: 50
        source_image: projects/rhel-cloud/global/image/rhel-8-v20190905
        zone: us-central1-a
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        state: present
      register: disk


