---
- name: Create Windows Server in GCP
  hosts: localhost
  gather_facts: no
  
  vars:
    cred_kind: serviceaccount
    machine_type: e2-standard-2
    source_image_family: windows-2022
    source_image_project: windows-cloud
  
    # Template variable dynamic
    # project_id: openenv-9bkwf
    # zone: us-central1-a
    # region: us-central1
    # instance_name: windows-server-test


  tasks:
    - name: create a disk mapped from windows-2022
      google.cloud.gcp_compute_disk:
        name: windows-disk-instance
        size_gb: "50"
        source_image: "projects/{{ source_image_project }}/global/images/family/{{ source_image_family }}"
        zone: "{{ zone }}"
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        state: present
      register: disk

    - name: create a VPC network
      google.cloud.gcp_compute_network:
        name: "{{ instance_name }}-network"
        auto_create_subnetworks: 'true'
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        state: present
      register: network

    - name: create a subnet
      google.cloud.gcp_compute_subnetwork:
        name: "{{ instance_name }}-subnet"
        region: "{{ region }}"
        network: "{{ network }}"
        ip_cidr_range: "172.16.0.0/16"
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        state: present
      register: subnet

    - name: create an public IP Address
      google.cloud.gcp_compute_address:
        name: "{{ instance_name }}-address"
        region: "{{ region }}"
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        state: present
      register: address

    - name: Create firewall rule to allow RDP
      google.cloud.gcp_compute_firewall:
        name: allow-tcp-traffic
        network: "{{ network }}"
        allowed:
          - ip_protocol: tcp
            ports: ["3389"]
        source_ranges: ["0.0.0.0/0"]
        target_tags: ["windows-server"]
        direction: INGRESS
        project: "{{ project_id }}"

    - name: Create a Windows Server VM instance
      google.cloud.gcp_compute_instance:
        name: "{{ instance_name }}"
        machine_type: "{{ machine_type }}"
        zone: "{{ zone }}"
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        disks:
          - auto_delete: true
            boot: true
            source: "{{ disk }}"
        network_interfaces:
          - network: "{{ network }}"
            subnetwork: "{{ subnet }}"
            access_configs:
              - name: External NAT
                nat_ip: "{{ address }}"
                type: ONE_TO_ONE_NAT
        metadata:
          windows-startup-script-cmd: |
            net user /add ansible_user MySecurePass123!
            net localgroup administrators ansible_user /add
        tags:
          items: windows-server
      register: instance

    - name: Print instance public IP
      ansible.builtin.debug:
        msg: "The window server ip is: {{ address.address }}"
