---
- name: Create a GCP instance
  hosts: localhost
  gather_facts: no
  
  vars:
    project_id: openenv-9bkwf
    cred_kind: serviceaccount
    zone: us-central1-a
    disk_size_gb: 50
    region: us-central1
    instance_name: rhel8
    machine_type: e2-standard-2

  tasks:
    - name: create a disk mapped from RHEL8 image
      google.cloud.gcp_compute_disk:
        name: rhel8-disk-instance
        size_gb: "{{ disk_size_gb }}"
        source_image: projects/rhel-cloud/global/images/rhel-8-v20190905
        zone: "{{ zone }}"
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        state: present
      register: disk

    - name: create a VPC network
      google.cloud.gcp_compute_network:
        name: network-instance
        auto_create_subnetworks: 'true'
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        state: present
      register: network

    - name: create a subnet
      google.cloud.gcp_compute_subnetwork:
        name: subnet-instance
        region: "{{ region }}"
        network: "{{ network }}"
        ip_cidr_range: "172.16.0.0/16"
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        state: present
      register: subnet
        

    - name: create an public IP Address
      google.cloud.gcp_compute_address:
        name: address-instance
        region: "{{ region }}"
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        state: present
      register: address

    - name: create firewall
      google.cloud.gcp_compute_firewall:
        name: firewall-instance
        network: "{{ network }}"
        allowed:
        - ip_protocol: tcp
          ports: ['22']
        source_ranges: [ '0.0.0.0/0' ]
        target_tags:
        - rhel-ssh
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        state: present
      register: firewall

    - name: create the RHEL8 instance
      google.cloud.gcp_compute_instance:
        name: "{{ instance_name }}"
        machine_type: "{{ machine_type }}"
        disks:
        - auto_delete: 'true'
          boot: 'true'
          source: "{{ disk }}"
        network_interfaces:
        - network: "{{ network }}"
          subnetwork: "{{ subnet }}"
          access_configs:
          - name: External NAT
            nat_ip: "{{ address }}"
            type: ONE_TO_ONE_NAT
        tags:
          items: rhel-ssh
        zone: "{{ zone }}"
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        state: present

    - name: Print instance public IP
      ansible.builtin.debug:
        msg: "The RHEL instance is accessible at {{ address.address }}"

          
          


