---
- name: Create Windows Server in GCP
  hosts: localhost
  gather_facts: no
  
  vars:
    cred_kind: serviceaccount

    # Template variable dynamic
    # project_id: 
    # zone: us-central1-a
    # region: us-central1
    # instance_name:

  tasks:
    - name: delete  Windows Server VM instance
      google.cloud.gcp_compute_instance:
        name: "{{ instance_name }}"
        zone: "{{ zone }}"
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        tags:
          items: windows-server
        state: absent

    - name: delete firewall rule
      google.cloud.gcp_compute_firewall:
        name: allow-tcp-traffic
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        state: absent

    - name: delete public IP Address
      google.cloud.gcp_compute_address:
        name: "{{ instance_name }}-address"
        region: "{{ region }}"
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        state: absent