---
- name: Create Windows Server in GCP
  hosts: localhost
  gather_facts: no
  
  vars:
    project_id: openenv-9bkwf
    cred_kind: serviceaccount
    zone: us-central1-a
    region: us-central1
    instance_name: windows-server-test
    machine_type: e2-standard-2
    source_image_family: windows-2022
    source_image_project: windows-cloud
    firewall_rule_name: allow-rdp
    disk_size_gb: 50
    source_ranges: ["0.0.0.0/0"]  
    target_tags: ["windows-server"]



  tasks:
    - name: Create a Windows Server VM instance
      google.cloud.gcp_compute_instance:
        name: "{{ instance_name }}"
        zone: "{{ zone }}"
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        tags:
          items: windows-server
        state: absent

    - name: Create firewall rule to allow RDP
      google.cloud.gcp_compute_firewall:
        name: "{{ firewall_rule_name }}"
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        state: absent

    - name: create an public IP Address
      google.cloud.gcp_compute_address:
        name: windows-address-instance
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        state: absent

    - name: create a subnet
      google.cloud.gcp_compute_subnetwork:
        name: windows-subnet-instance
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        state: absent

    - name: create a VPC network
      google.cloud.gcp_compute_network:
        name: windows-network-instance
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        state: absent
