---
- name: Create Windows Server in GCP
  hosts: localhost
  gather_facts: no
  
  vars:
    project_id: openenv-9bkwf
    cred_kind: serviceaccount
    instance_name: windows-server-test
    firewall_rule_name: allow-tcp-traffic
    zone: us-central1-a
    region: us-central1


  tasks:
    - name: delete  Windows Server VM instance
      google.cloud.gcp_compute_instance:
        name: "{{ instance_name }}"
        zone: "{{ zone }}"
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        tags:
          items: windows-server
        state: absent

    - name: delete firewall rule
      google.cloud.gcp_compute_firewall:
        name: "{{ firewall_rule_name }}"
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        state: absent

    - name: delete public IP Address
      google.cloud.gcp_compute_address:
        name: windows-address-instance
        region: "{{ region }}"
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        state: absent

    - name: delete subnet
      google.cloud.gcp_compute_subnetwork:
        name: windows-subnet-instance
        ip_cidr_range: "172.16.0.0/16"
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        state: absent

    - name: delete VPC network
      google.cloud.gcp_compute_network:
        name: windows-network-instance
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"
        state: absent
