---
- name: Create Windows Server in GCP
  hosts: localhost
  gather_facts: no
  
  vars:
    # Template variable dynamic
    # project_id: openenv-9bkwf
    # network-instance: 

  tasks:
    - name: Create firewall rule to allow RDP
      google.cloud.gcp_compute_firewall:
        name: allow-rdp
        network: "global/networks/{{ network-instance }}"
        allowed:
          - ip_protocol: tcp
            ports: ["3389"]
        source_ranges: ["0.0.0.0/0"]
        target_tags: ["windows-server"]
        direction: INGRESS
        project: "{{ project_id }}"

