---
- name: Create Windows Server in GCP
  hosts: localhost
  gather_facts: no
  
  vars:
    # Template variable dynamic
    # project_id: openenv-9bkwf
    # network-instance: 
    source_ranges: ["0.0.0.0/0"]  # ⚠️ Open to all — consider restricting this!
    target_tags: ["windows-server"]  # Match the tag used in the VM playbook

  tasks:
    - name: Create firewall rule to allow RDP
      google.cloud.gcp_compute_firewall:
        name: allow-rdp
        network: "global/networks/{{ instance-name }}-network"
        allowed:
          - ip_protocol: tcp
            ports: ["3389"]
        source_ranges: "{{ source_ranges }}"
        target_tags: "{{ target_tags }}"
        direction: INGRESS
        project: "{{ project_id }}"

