---
- name: Open RDP port on network
  hosts: localhost
  gather_facts: no
  
  vars:
    # Template variable dynamic
    # project_id: 
    # network-instance: 

    cred_kind: serviceaccount
    source_ranges: ["0.0.0.0/0"]  
    target_tags: ["windows-server"]

  tasks:
    - name: Create firewall rule to allow RDP
      google.cloud.gcp_compute_firewall:
        name: allow-rdp
        network: "{{ instance_name }}-network"
        allowed:
          - ip_protocol: tcp
            ports: ["3389"]
        source_ranges: "{{ source_ranges }}"
        target_tags: "{{ target_tags }}"
        direction: INGRESS
        project: "{{ project_id }}"
        auth_kind: "{{ cred_kind }}"

